name: 'Formula: Foundational'
description: 'Recipe to build foundational functionality in Drupal.'
type: 'Site'

install:
  - config
  - datetime
  - entity_reference_revisions
  - field_ui
  - focal_point
  - help
  - layout_paragraphs
  - link
  - media
  - media_library
  - menu_link_content
  - menu_ui
  - node
  - nomarkup
  - options
  - paragraphs
  - pathauto
  - taxonomy
  - toolbar
  - views
  - views_ui
  - claro
  - olivero
config:
  actions:
    node.type.page:
      simple_config_update:
        langcode: en
        status: true
        dependencies:
          module:
            - menu_ui
        third_party_settings:
          menu_ui:
            available_menus:
              - main
            parent: 'main:'
        _core:
          default_config_hash: i0snV8Wj--OkRW12UdachUiYiz3FbeMwHu_pZYfzKLc
        name: 'Basic page'
        type: page
        description: 'Use <em>basic pages</em> for most content.'
        help: null
        new_revision: true
        preview_mode: 1
        display_submitted: false
    core.entity_form_display.node.page.default:
      simple_config_update:
        langcode: en
        status: true
        dependencies:
          config:
            - field.field.node.page.field_content
            - field.field.node.page.field_summary_text
            - node.type.page
          module:
            - layout_paragraphs
            - path
            - text
        id: node.page.default
        targetEntityType: node
        bundle: page
        mode: default
        content:
          created:
            type: datetime_timestamp
            weight: 5
            region: content
            settings: {  }
            third_party_settings: {  }
          field_content:
            type: layout_paragraphs
            weight: 2
            region: content
            settings:
              view_mode: default
              preview_view_mode: default
              form_display_mode: default
              nesting_depth: 0
              require_layouts: 0
              empty_message: ''
            third_party_settings: {  }
          field_summary_text:
            type: text_textarea
            weight: 3
            region: content
            settings:
              rows: 5
              placeholder: ''
            third_party_settings: {  }
          path:
            type: path
            weight: 8
            region: content
            settings: {  }
            third_party_settings: {  }
          promote:
            type: boolean_checkbox
            weight: 6
            region: content
            settings:
              display_label: true
            third_party_settings: {  }
          status:
            type: boolean_checkbox
            weight: 9
            region: content
            settings:
              display_label: true
            third_party_settings: {  }
          sticky:
            type: boolean_checkbox
            weight: 7
            region: content
            settings:
              display_label: true
            third_party_settings: {  }
          title:
            type: string_textfield
            weight: 0
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings: {  }
          uid:
            type: entity_reference_autocomplete
            weight: 4
            region: content
            settings:
              match_operator: CONTAINS
              match_limit: 10
              size: 60
              placeholder: ''
            third_party_settings: {  }
        hidden: {  }
    core.entity_view_display.node.page.default:
      simple_config_update:
        langcode: en
        status: true
        dependencies:
          config:
            - field.field.node.page.field_content
            - field.field.node.page.field_summary_text
            - node.type.page
          module:
            - layout_paragraphs
            - user
        id: node.page.default
        targetEntityType: node
        bundle: page
        mode: default
        content:
          field_content:
            type: layout_paragraphs
            label: hidden
            settings:
              view_mode: default
              link: ''
            third_party_settings: {  }
            weight: 1
            region: content
          links:
            settings: {  }
            third_party_settings: {  }
            weight: 2
            region: content
        hidden:
          field_summary_text: true
    core.entity_view_display.node.page.teaser:
      simple_config_update:
        langcode: en
        status: true
        dependencies:
          config:
            - core.entity_view_mode.node.teaser
            - field.field.node.page.field_content
            - field.field.node.page.field_summary_text
            - node.type.page
          module:
            - text
            - user
        id: node.page.teaser
        targetEntityType: node
        bundle: page
        mode: teaser
        content:
          field_summary_text:
            type: text_default
            label: hidden
            settings: {  }
            third_party_settings: {  }
            weight: 1
            region: content
          links:
            weight: 101
            region: content
        hidden:
          field_content: true
